queue_rules:
  - name: default
    conditions:
      - "check-success~=run-e2e-tests"
      - "check-success=security/snyk (nationalarchives)"
pull_request_rules:
  - name: automatic merge for Scala Steward
    conditions:
      - author=tna-digital-archiving-jenkins
      - "check-success~=run-e2e-tests"
      - "check-success=security/snyk (nationalarchives)"
      - or:
          - files=build.sbt
          - files~=^(!?project/)
    actions:
      review:
        type: APPROVE
        message: Automatically approving Scala Steward
      queue:
        name: default
