name: End to end tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser used to run the tests'
        required: false
        default: 'Firefox'
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
        default: 'intg'
      wait:
        description: 'The time in seconds to wait before starting the tests'
        required: false
        default: '0'
permissions:
  id-token: write
  contents: read
run-name:  ${{ github.event_name != 'pull_request' && format('End to end tests ({0})', inputs.environment) || '' }}
jobs:
  setup-e2e-tests:
    concurrency: ${{ github.event.inputs.environment != '' && github.event.inputs.environment || 'intg' }}
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.generate-files.outputs.files }}
      environment: ${{ steps.set-secret-names.outputs.environment }}
      account_number_secret: ${{ steps.set-secret-names.outputs.account_number_secret }}
      title_environment: ${{ steps.set-secret-names.outputs.title_environment }}
      is_pr: ${{ steps.set-secret-names.outputs.is_pr }}
      last_status: ${{ steps.get-last-status.outputs.last_status }}
      driver: ${{ steps.get-driver.outputs.driver }}
      browser: ${{ steps.get-driver.outputs.browser }}
    steps:
      - name: Wait
        run: sleep ${{ github.event.inputs.wait != '' && github.event.inputs.wait || '0' }}
      - name: Checkout
        uses: actions/checkout@v3
      - id: get-driver
        run: python .github/scripts/get_driver_location.py ${{ github.event.inputs.browser }}
      - id: get-last-status
        run: pip install requests && python .github/scripts/get_last_status.py
      - id: set-secret-names
        run: python .github/scripts/set_secret_names.py ${{ github.event.inputs.environment }}
      - name: Set feature file names
        id: generate-files
        run: |
          FILES=$(ls src/test/resources/features/ | jq -R -s -c 'split("\n")[:-1]')
          echo files=${FILES} >> $GITHUB_OUTPUT
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[steps.set-secret-names.outputs.account_number_secret] }}:role/TDRGithubActionsGetE2ESecretsRole${{ steps.set-secret-names.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: GetKeycloakSecrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[steps.set-secret-names.outputs.account_number_secret] }}:role/TDRUpdateWAFAndSecurityGroupsRole${{ steps.set-secret-names.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: UpdateWAF
      - name: Get current IPs from WAF
        run: .github/scripts/update-waf-ipset.sh GET ${{ github.event.inputs.environment }}
      - name: Upload WAF IP as artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: waf-ip-artifacts-${{ matrix.file }}
          path: waf-ip.txt
  run-e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - setup-e2e-tests
    strategy:
      matrix:
        file: ${{ fromJSON(needs.setup-e2e-tests.outputs.files) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRGithubActionsGetE2ESecretsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: GetKeycloakSecrets
      - id: get-keycloak-secrets
        run: pip install boto3 && python .github/scripts/get_keycloak_secrets.py ${{ github.event.inputs.environment }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRUpdateWAFAndSecurityGroupsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: UpdateWAF
      - name: Get runner IP
        run: curl https://ipinfo.io/ip > ${{ matrix.file }}-ip.txt
      - name: Upload runner IP as artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ip-artifacts-${{ matrix.file }}
          path: ${{ matrix.file }}-ip.txt
      - name: Update security group
        run: .github/scripts/update-security-group.sh INSERT ${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}
      - name: Update WAF ipset
        run: .github/scripts/update-waf-ipset.sh INSERT ${{ github.event.inputs.environment }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRGithubActionsRunE2ETestsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: E2ETests
      - name: Run Tests
        env:
          DRIVER_LOCATION: ${{ needs.setup-e2e-tests.outputs.driver }}
        run: sbt test -Daccount.number=${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }} -Dconfig.file=./src/test/resources/application.${{ needs.setup-e2e-tests.outputs.environment }}.conf -Dkeycloak.user.admin.secret=${{ steps.get-keycloak-secrets.outputs.user_admin_secret }} -Dkeycloak.backendchecks.secret=${{ steps.get-keycloak-secrets.outputs.backend_checks_secret }} -Dbrowser=${{ needs.setup-e2e-tests.outputs.browser }} -Dcucumber.features=./src/test/resources/features/${{ matrix.file }}
      - name: Configure AWS credentials
        if: ${{ always() }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRUpdateWAFAndSecurityGroupsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: UpdateWAF

  remove-access:
    needs: [run-e2e-tests, setup-e2e-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download IP artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: ip-artifacts
          pattern: ip-artifacts-*
          merge-multiple: true
      - name: Download WAF IP artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: waf-ip-artifacts
          pattern: waf-ip-artifacts-*
          merge-multiple: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRUpdateWAFAndSecurityGroupsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: UpdateWAF
      - name: Remove each IP from security group
        run: |
          for ip_file in ip-artifacts/*; do
            if [ -f "$ip_file" ]; then
              ip=$(cat "$ip_file")
              echo "Revoking IP: $ip from security group"
              .github/scripts/update-security-group.sh DELETE "$ip"
            else
              echo "$ip_file is not a file, skipping..."
            fi
          done
      - name: Remove WAF ipset
        run: .github/scripts/update-waf-ipset.sh DELETE ${{ github.event.inputs.environment }}

  send-messages:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - run-e2e-tests
      - setup-e2e-tests
    steps:
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: ${{ needs.run-e2e-tests.result=='failure' && needs.setup-e2e-tests.outputs.is_pr == 'False' }}
        with:
          message: ":warning: E2E tests have failed for environment ${{ needs.setup-e2e-tests.outputs.environment }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: ${{ needs.run-e2e-tests.result=='success' && needs.setup-e2e-tests.outputs.is_pr == 'False' && needs.setup-e2e-tests.outputs.last_status != 'success' }}
        with:
          message: ":white_check_mark: E2E tests have succeeded after previous failure for environment ${{ needs.setup-e2e-tests.outputs.environment }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
