name: End to end tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser used to run the tests'
        required: false
        default: 'Firefox'
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
        default: 'intg'
      wait:
        description: 'The time in seconds to wait before starting the tests'
        required: false
        default: '0'
permissions:
  id-token: write
  contents: read
jobs:
  setup-e2e-tests:
    concurrency: ${{ github.workflow }}
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.generate-files.outputs.files }}
      environment: ${{ steps.set-secret-names.outputs.environment }}
      account_number_secret: ${{ steps.set-secret-names.outputs.account_number_secret }}
      title_environment: ${{ steps.set-secret-names.outputs.title_environment }}
      is_pr: ${{ steps.set-secret-names.outputs.is_pr }}
      last_status: ${{ steps.get-last-status.outputs.last_status }}
      driver: ${{ steps.get-driver.outputs.driver }}
      browser: ${{ steps.get-driver.outputs.browser }}
    steps:
      - name: Wait
        run: sleep ${{ github.event.inputs.wait != '' && github.event.inputs.wait || '0' }}
      - name: Checkout
        uses: actions/checkout@v3
      - id: get-driver
        run: python .github/scripts/get_driver_location.py ${{ github.event.inputs.browser }}
      - id: get-last-status
        run: pip install requests && python .github/scripts/get_last_status.py
      - id: set-secret-names
        run: python .github/scripts/set_secret_names.py ${{ github.event.inputs.environment }}
      - name: Set feature file names
        id: generate-files
        run: |
          FILES=$(ls src/test/resources/features/ | jq -R -s -c 'split("\n")[:-1]')
          echo files=${FILES} >> $GITHUB_OUTPUT
  run-e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - setup-e2e-tests
    strategy:
      matrix:
        file: ${{ fromJSON(needs.setup-e2e-tests.outputs.files) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRGithubActionsGetE2ESecretsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: GetKeycloakSecrets
      - id: get-keycloak-secrets
        run: pip install boto3 && python .github/scripts/get_keycloak_secrets.py ${{ github.event.inputs.environment }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRUpdateWAFAndSecurityGroupsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: UpdateWAF
      - name: Get public IP
        run: curl https://ipinfo.io/ip > ${{ runner.os }}-${{ matrix.file }}-ip.txt
      - name: Upload IP as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ip-artifacts
          path: ${{ runner.os }}-${{ matrix.file }}-ip.txt
      - name: Update security group
        run: .github/scripts/update-security-group.sh INSERT ${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRGithubActionsRunE2ETestsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: E2ETests
      - name: Run Tests
        env:
          DRIVER_LOCATION: ${{ needs.setup-e2e-tests.outputs.driver }}
        run: sbt test -Daccount.number=${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }} -Dconfig.file=./src/test/resources/application.${{ needs.setup-e2e-tests.outputs.environment }}.conf -Dkeycloak.user.admin.secret=${{ steps.get-keycloak-secrets.outputs.user_admin_secret }} -Dkeycloak.backendchecks.secret=${{ steps.get-keycloak-secrets.outputs.backend_checks_secret }} -Dbrowser=${{ needs.setup-e2e-tests.outputs.browser }} -Dcucumber.features=./src/test/resources/features/${{ matrix.file }}
      - name: Configure AWS credentials
        if: ${{ always() }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}:role/TDRUpdateWAFAndSecurityGroupsRole${{ needs.setup-e2e-tests.outputs.title_environment }}
          aws-region: eu-west-2
          role-session-name: UpdateWAF
      - name: Remove access
        if: ${{ always() }}
        run: .github/scripts/update-security-group.sh DELETE ${{ secrets[needs.setup-e2e-tests.outputs.account_number_secret] }}
  print-ips:
    needs: run-e2e-tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          name: ip-artifacts
          path: ip-artifacts

      - name: Extract and print IPs
        run: |
          cat ip-artifacts/* | tr '\n' ' '
  send-messages:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - run-e2e-tests
      - setup-e2e-tests
    steps:
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: ${{ needs.run-e2e-tests.result=='failure' && needs.setup-e2e-tests.outputs.is_pr == 'False' }}
        with:
          message: ":warning: E2E tests have failed for environment ${{ needs.setup-e2e-tests.outputs.environment }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: ${{ needs.run-e2e-tests.result=='success' && needs.setup-e2e-tests.outputs.is_pr == 'False' && needs.setup-e2e-tests.outputs.last_status != 'success' }}
        with:
          message: ":white_check_mark: E2E tests have succeeded after previous failure for environment ${{ needs.setup-e2e-tests.outputs.environment }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
